name:                reversi
version:             0.1.0.0
github:              "githubuser/reversi"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/reversi#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 0.7
- gtk3 >= 0.15
- cairo >= 0.13

library:
  source-dirs: src

executables:
  reversi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reversi

tests:
  reversi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reversi

benchmarks:
  reversi-bench:
    main:                Benchmark.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-p
    - -fprof-auto
    - -fforce-recomp
    dependencies:
    - reversi
